server:
  port: 9501
  tomcat:
    accesslog:
      enabled: true
    threads:
      min-spare: 300
      max: 3000
    connection-timeout: 10000
  servlet:
    encoding:
      force: true
      charset: UTF-8

spring:
  application:
    name: employee-client

service:
  baseUrl: "/services/employee-client"
  swagger:
    version: 'version1.0.0-1403/04/31'
    title: 'employee client'
    description: 'employee client'
  employee:
    name: employee


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: ${spring.application.name}
    hostname: localhost